import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsContact: SidebarsConfig = {
  contactSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsContact;